spring:
  application:
    name: register-service  # Service registers under this name
  thymeleaf:
    enabled: false

# Configure this Discovery Server
eureka:
  instance:
    hostname: localhost
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
     
server:
  port: 1111   # HTTP (Tomcat) port


