# Spring properties
spring:
  application:
    name: web-service  # Identify this application
  http:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB

eureka:
  instance:
     prefer-ip-address: true
     ip-address: 10.10.2.25
     leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
  client:
    serviceUrl: 
      defaultZone: http://localhost:1111/eureka/
# HTTP Server
server:
  port: 80   # HTTP (Tomcat) port

image:
  location:
    path: D:/